version: '3.4'
services:
  bot:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ../.env
    command: start:watch
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/opt/app
    ports:
      - 5858:5858
  db:
    image: mongo
    ports:
      - "$EXPOSED_DB_PORT:27017"